# Intended to match execution client config as part of:
# https://github.com/parithosh/consensus-deployment-ansible/tree/pithos/scripts/quick-run
version: '3.4'
services:
  start_ethereumjs_client:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: ethereumjs_client
    volumes:
      - ./execution_data:/execution_data
      - ../../$TESTNET_NAME/custom_config_data:/custom_config_data
    network_mode: host
    command: >
      --datadir=/execution_data --gethGenesis=./ethereumjs-monorepo/packages/client/pithos/genesis.json --rpc --rpcEngine --rpcEnginePort=8545 --rpcStubGetLogs --rpcDebug --loglevel=debug --bootnodes=$ENODE --extIP=$IP_ADDRESS
