---
api.rest.enabled: true
api.rest.host: 0.0.0.0
api.rest.api: '*'
logFile: beacon.log
logLevelFile: debug
logRotate: true
logMaxFiles: 5
eth1.enabled: true
eth1.disableEth1DepositDataTracker: true
eth1.providerUrls: http://localhost:8545
execution.urls: http://localhost:8550
paramsFile: pithos/config.yaml
genesisStateFile: pithos/genesis.ssz
network.bootMultiaddrs: /ip4/35.178.114.73/tcp/9000/p2p/16Uiu2HAkz6oRBK6aKRA2uv9vxJEPhc2Rmznd5D1DqE4DoCYNqnf3
network.discv5.bootEnrs: enr:-Iq4QKuNB_wHmWon7hv5HntHiSsyE1a6cUTK1aT7xDSU_hNTLW3R4mowUboCsqYoh1kN9v3ZoSu_WuvW9Aw0tQ0Dxv6GAXxQ7Nv5gmlkgnY0gmlwhLKAlv6Jc2VjcDI1NmsxoQK6S-Cii_KmfFdUJL2TANL3ksaKUnNXvTCv1tLwXs0QgIN1ZHCCIyk
network.discv5.enabled: true
network.connectToDiscv5Bootnodes: true
