name: Account Test
'on':
  push:
    branches:
      - master
    tags:
      - '*'
    paths-ignore:
      - packages/block/**
      - packages/blockchain/**
      - packages/common/**
      - packages/tx/**
  pull_request:
    types: [opened, reopened, synchronize]
    paths-ignore:
      - packages/block/**
      - packages/blockchain/**
      - packages/common/**
      - packages/tx/**
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 13.x]
    steps:
      - name: 'Use Node.js ${{ matrix.node-version }}'
        uses: actions/setup-node@v1
        with:
          node-version: '${{ matrix.node-version }}'
      - uses: actions/checkout@v1
      - run: npx lerna bootstrap --scope ethereumjs-account --ignore-scripts --include-dependencies --no-ci
      - run: npx lerna run --scope ethereumjs-account --include-dependencies build
      - run: npm test
        env:
          CI: true
        working-directory: '${{ env.cwd }}'
    env:
      cwd: '${{github.workspace}}/packages/account'
