name: Block
branding:
  icon: 'box'
  color: 'orange'
on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  test-block:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10, 12, 13, 14]
    env:
      cwd: ${{github.workspace}}/packages/block
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/checkout@v1

      - run: npm install
        working-directory: ${{ env.cwd }}

      - run: npx lerna run lint --scope ethereumjs-block

      - run: npm run coverage
        working-directory: ${{ env.cwd }}

      - uses: codecov/codecov-action@v1
        with:
          file: ${{ env.cwd }}/coverage/lcov.info
          flags: block
        if: ${{ matrix.node-version == 12 }}
