name: Block
on:
  workflow_call:
    inputs:
      dep-cache-key:
        required: true
        type: string
      build-cache-key:
        required: true
        type: string
  workflow_dispatch:

env:
  cwd: ${{github.workspace}}/packages/block

defaults:
  run:
    working-directory: packages/block

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}-block
  cancel-in-progress: true

jobs:
  test-block:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          
      - uses: actions/cache/restore@v4
        id: dep-cache
        with:
          path: ${{github.workspace}}
          key: ${{ inputs.dep-cache-key }}
  
      # - uses: actions/cache/restore@v4
      #   id: build-cache
      #   with:
      #     path: ${{github.workspace}}/packages
      #     key: ${{ inputs.build-cache-key }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install Dependencies
        if: steps.dep-cache.outputs.cache-hit != 'true'
        run: npm ci     
        working-directory: ${{ github.workspace }}
            
      # - name: Build packages
      #   # if: steps.build-cache.outputs.cache-hit != 'true'
      #   run: npm run postinstall 
      #   working-directory: ${{ github.workspace }}  

      - run: npm run lint      
      - run: npm run coverage
      - uses: codecov/codecov-action@v3
        with:
          files: ${{ github.workspace}}/packages/block/coverage/lcov.info
          flags: block
