name: Blockchain Lint
'on':
  push:
    branches:
      - master
    tags:
      - '*'
    paths-include:
      - packages/blockchain/**
  pull_request:
    types: [opened, reopened, synchronize]
    paths-include:
      - packages/blockchain/**
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: actions/checkout@v1
      - run: npx lerna bootstrap --scope ethereumjs-blockchain --ignore-scripts --include-dependencies --no-ci
      - run: npx lerna run --scope ethereumjs-blockchain --include-dependencies build
      - run: npm run lint
        env:
          CI: true
        working-directory: '${{ env.cwd }}'
    env:
      cwd: '${{github.workspace}}/packages/blockchain'
