name: Browser
on:
  workflow_call:
    inputs:
      dep-cache-key:
        required: true
        type: string
      submodule-cache-key:
          required: true
          type: string
  workflow_dispatch:

env:
  cwd: ${{github.workspace}}

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}-browser
  cancel-in-progress: true

jobs:
  test-all-browser:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - if: github.event_name == 'workflow_dispatch'
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - if: github.event_name == 'workflow_call'
        uses: actions/checkout@v4    

      - uses: actions/cache/restore@v4
        id: dep-cache
        with:
          path: ${{github.workspace}}
          key: ${{ inputs.dep-cache-key }}
  
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies (if not restored from cache)
        if: steps.dep-cache.outputs.cache-hit != 'true'
        run: npm ci     
        working-directory: ${{ github.workspace }}

      - uses: actions/cache/restore@v4
        name: Initialize ethereum-tests
        id: submodules-cache
        with:
          path: ${{github.workspace}}/packages/ethereum-tests
          key: ${{ inputs.submodule-cache-key }}

      - run: npm run install-browser-deps

      - run: npm run test:browser --workspaces --if-present



