name: Browser
on:
  workflow_call:
    inputs:
      dep-cache-key:
        required: true
        type: string
  workflow_dispatch:

env:
  cwd: ${{github.workspace}}

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}

jobs:
  test-all-browser:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive # necessary for block tests to load ethereum/tests
          
      - uses: actions/cache/restore@v4
        id: dep-cache
        with:
          path: ${{github.workspace}}
          key: ${{ inputs.dep-cache-key }}
  
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install Dependencies (if not restored from cache)
        if: steps.dep-cache.outputs.cache-hit != 'true'
        run: npm ci     
        working-directory: ${{ github.workspace }}
              
            
      - run: npm ci
      - run: npm run install-browser-deps

      - run: npm run test:browser --workspaces --if-present



