name: Browser
on:
  push:
    branches: [master, develop]
    tags: ['*']
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

env:
  cwd: ${{github.workspace}}

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test-all-browser:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16]
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm ci

# Install playwright dependencies
      - run: npx playwright install-deps

      - run: npm run lint
      - run: npm run test:browser -w=@ethereumjs/rlp
      - run: npm run test:browser -w=@ethereumjs/util
#     Provider, Account, and Address tests are skipped as currently failing
      - run: npm run test:browser -w=@etheruemjs/common
#     Trie: several tests not passing yet
#     - run: cd ../trie && npm run test:browser
      - run: npm run test:browser -w=@ethereumjs/tx
#     Block: serveral tests not passing yet
#     - run: cd ../block && npm run test:browser
#     No browser tests for devp2p
#     Blockchain: strange errors, needs another look
#     - run: cd ../blockchain && npm run test:browser
#     No browser tests for ethash
#     EVM: several tests not passing yet
#     - run: cd ../evm && npm run test:browser
#     StateManager: selected tests not passing yet
#     - run: cd ../statemanager && npm run test:browser
#     Wallet: import failing
#     - run: cd ../wallet && npm run test:browser
#     VM: several tests not passing yet
#     - run: cd ../vm && npm run test:browser

