name: Client
on:
  workflow_call:
    inputs:
      dep-cache-key:
        required: true
        type: string
  workflow_dispatch:

env:
  cwd: ${{github.workspace}}/packages/client

defaults:
  run:
    working-directory: packages/client

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

# TODO FIXME (this entire file)

jobs:
  test-client:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache/restore@v4
        id: dep-cache
        with:
          path: ${{github.workspace}}
          key: ${{ inputs.dep-cache-key }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install Dependencies (if not restored from cache)
        if: steps.dep-cache.outputs.cache-hit != 'true'
        run: npm ci     
        working-directory: ${{ github.workspace }}

      - run: npm run coverage
      - uses: codecov/codecov-action@v3
        with:
          files: ${{ env.cwd }}/coverage/lcov.info
          flags: client
      - uses: nick-fields/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: cd ${{github.workspace}}/packages/client && npm run test:integration

      - run: npm run lint

  test-client-dockerfile:
    name: test client docker file
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build from source
        run: >
          docker buildx build .
          --tag ethereumjs:local
          --platform linux/amd64
          --build-arg COMMIT=$(git rev-parse HEAD)
        working-directory: ${{github.workspace}}

  test-client-cli:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - uses: actions/checkout@v4

      - uses: actions/cache/restore@v4
        id: dep-cache
        with:
          path: ${{github.workspace}}
          key: ${{ inputs.dep-cache-key }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install Dependencies (if not restored from cache)
        if: steps.dep-cache.outputs.cache-hit != 'true'
        run: npm ci     
        working-directory: ${{ github.workspace }}


      - run: cd ${{github.workspace}}/packages/client && npx vitest run test/cli/cli

      - run: npm i wtfnode

      - uses: nick-fields/retry@v2
        with:
          timeout_minutes: 2
          max_attempts: 1
          command: cd ${{github.workspace}}/packages/client && npx wtfnode ../../node_modules/tape/bin/tape -r ts-node/register './test/**/*.spec.ts'
