name: Common
on:
  push:
    branches: [master, develop]
    tags: ['*']
  pull_request:
    types: [opened, reopened, synchronize]

env:
  cwd: ${{github.workspace}}/packages/common

defaults:
  run:
    working-directory: packages/common

jobs:
  test-common:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm i
        working-directory: ${{github.workspace}}

      - run: npm run coverage

      - uses: codecov/codecov-action@v2
        with:
          file: ${{ env.cwd }}/coverage/lcov.info
          flags: common
        if: ${{ matrix.node-version == 16 }}

      - run: npm run lint
