name: E2E Hardhat Tests
on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    types: [opened, reopened, synchronize]
    
env:
  cwd: ${{github.workspace}}

jobs:
  e2e-hardhat:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15]
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      # Installs all dependencies, bootstrapping everything.
      - run: npm install

      # Publishes all packages to a virtual npm registry after giving each a minor version bump
      - name: Publish to virtual registry
        run: npm run e2e:publish

      - name: Generate e2e resolutions
        run: npm run e2e:resolutions

      # Clones repo and injects proxied dependencies
      - name: Build hardhat and test with new EthereumJS dependencies
        run: bash ./scripts/e2e-hardhat.sh
        env:
          INFURA_URL: ${{ secrets.URL_MAINNET }}
          