name: genesis
on:
  workflow_call:
    inputs:
      dep-cache-key:
        required: false
        type: string
  workflow_dispatch:
    inputs:
      dep-cache-key:
        required: false
        type: string

env:
  cwd: ${{github.workspace}}/packages/genesis

defaults:
  run:
    working-directory: packages/genesis

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}-genesis
  cancel-in-progress: true

jobs:
  test-genesis:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/checkout@v4

      - uses: actions/cache/restore@v4
        id: dep-cache
        with:
          path: ${{github.workspace}}
          key: ${{ inputs.dep-cache-key }}

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies (if not restored from cache)
        if: steps.dep-cache.outputs.cache-hit != 'true'
        run: npm ci     
        working-directory: ${{ github.workspace }}
    

      - run: npm run lint
      
      - run: npm run coverage
      - uses: codecov/codecov-action@v3
        with:
          files: ${{ env.cwd }}/coverage/lcov.info
          flags: genesis

      - run: npm run test:node 