name: Typecheck (tsc)
on:
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  run-typecheck:
    runs-on: ubuntu-latest
    steps:
      # We clone the repo and submodules if triggered from work-flow dispatch
      - if: inputs.submodule-cache-key == 'none'
        uses: actions/checkout@v4

      # We restore the code/deps from cache if triggered from workflow_call (i.e. have valid cache key)
      - if: inputs.dep-cache-key != 'none'
        uses: actions/cache/restore@v4
        id: dep-cache
        with:
          path: ${{github.workspace}}
          key: ${{ inputs.dep-cache-key }}

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies (if not restored from cache)
        if: steps.dep-cache.outputs.cache-hit != 'true'
        run: npm ci
        working-directory: ${{ github.workspace }}

      - name: Typecheck
        run: npm run tsc --workspaces
        working-directory: ${{ github.workspace }}
